---
title: "Masterskript mit allem und Scharf"
---

```{r setup, include=FALSE}

# ---------------------------------------------------------------------------
# Einige Funktionen und Variabeln sind in die Datei 'prelude.R' ausgelagert.
# Diese werden hier nachgeladen und angepasst.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
source("prelude.R")
initPrelude(
    "MASTER-",       # Prefix f端r Terminlisten etc.
    TRUE           # Soll gepr端ft werden ob alle Pakete installiert sind?
)

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Sichert zu, dass die entsprechenden Daten auch vorhanden sind. 
# Ggf. werden sie von dem 端bergebenden Link geladen und lokal gespeichert.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
tips <- assertData("tips.csv", "https://goo.gl/whKjnl")

# ---------------------------------------------------------------------------
```

```{r child = './Inhalte/DES-Organisatorisches.Rmd'}
```

```{r child = './Inhalte/PraDa-Organisatorisches.Rmd'}
```

```{r child = './Inhalte/QMEval-Organisatorisches.Rmd'}
```

```{r child = './Inhalte/QFM-Organisatorisches.Rmd'}
```

```{r child = './Inhalte/WM-Organisatorisches.Rmd'}
```

```{r child = './Inhalte/WMQD-Organisatorisches.Rmd'}
```

```{r child = './Inhalte/Organisatorisches/Hinweise.Rmd'}
```

```{r child = './Inhalte/Grundlagen-Wissenschaft.Rmd'}
```

```{r child = './Inhalte/Fragebogen.Rmd'}
```

```{r child = './Inhalte/Grundlagen-QuantDat.Rmd'}
```

```{r child = './Inhalte/Einfuehrung-R.Rmd'}
```

```{r child = './Inhalte/Einfuehrung-EDA.Rmd'}
```

```{r child = './Inhalte/Einfuehrung-EDA-R.Rmd'}
```

```{r child = './Inhalte/Einfuehrung-Inferenz.Rmd'}
```

```{r child = './Inhalte/Einfuehrung-Wahrscheinlichkeit.Rmd'}
```

```{r child = './Inhalte/Einfuehrung-Normalverteilung.Rmd'}
```

```{r child = './Inhalte/Inferenz-Kategorial.Rmd'}
```

```{r child = './Inhalte/Inferenz-Numerisch.Rmd'}
```

```{r child = './Inhalte/Regression.Rmd'}
```

```{r child = './Inhalte/LogistischeRegression.Rmd'}
```

```{r child = './Inhalte/NaiveBayes.Rmd'}
```

```{r child = './Inhalte/Indexzahlen.Rmd'}
```

```{r child = './Inhalte/Gini.Rmd'}
```

```{r child = './Inhalte/Cluster.Rmd'}
```

```{r child = './Inhalte/Cluster-hclust.Rmd'}
```

```{r child = './Inhalte/PCA.Rmd'}
```

```{r child = './Inhalte/PLS-PM.Rmd'}
```

```{r child = './Inhalte/SNA.Rmd'}
```

<!-- ```{r child = './Inhalte/T-Textmining.Rmd'}
``` -->

```{r child = './Inhalte/Baumverfahren.Rmd'}
```

```{r child = './Inhalte/Assoziationsanalyse.Rmd'}
```

```{r child = './Inhalte/Evaluation.Rmd'}
```

```{r child = './Inhalte/Datenhandling.Rmd'}
```

```{r child = './Inhalte/Wiederholung-R.Rmd'}
```

```{r child = './Inhalte/Abschluss.Rmd'}
```

```{r child = './Inhalte/Charta.Rmd'}
```


```{r finalize, include=FALSE}
# ---------------------------------------------------------------------------
# Setzt einige Parameter zur端ck
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
finalizePrelude()
```
