---
title: "Quantitative Forschungsmethoden"
---

```{r setup, include=FALSE}
# ---------------------------------------------------------------------------
# Einige Funktionen und Variabeln sind in die Datei 'prelude.R' ausgelagert.
# Diese werden hier nachgeladen und angepasst.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
source("prelude.R")
initPrelude(
    "QFM-",        # Prefix für Terminlisten etc.
    TRUE           # Soll geprüft werden ob alle Pakete installiert sind?
)
```
```{r localKnitrButtonSetup, eval=!RENDEREDBYSCRIPT, echo=FALSE, include=FALSE}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Einstellungen für den Fall, dass man den knitr-Button nutzt. Sonst bitte
# 'eval=FALSE' einstellen!
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if (!exists("prelude.rendertools")) {
    loadPrelude("prelude_rendertools.R")
}

assign("abschluss", FALSE, envir = .GlobalEnv)

my.options$set(
  privateVorstellung = FALSE,   # Zeige die Private Vorstellung
  showVorlesungsplan = FALSE,   # Zeige die Vorlesungstermine -> In der Datei WMQD-default.Rmd anpassen
  Virtuell = FALSE,
  UseCache = TRUE,
  eufom = FALSE
)

createPrivateYaml("FOM-Dozent*in", "SoSe 2024", "FOM")
#if_else(my.options$get("eufom"),
#        createPrivateYaml("FOM-Dozent*in", "SoSe 2021", "FOM"),
#        createPrivateYaml("eufom-Dozent*in", "SoSe 2021", "eufom"))


assign("UseCache", TRUE, envir = .GlobalEnv)  # immer mal wieder auf FALSE setzen
assign("Vorlesungstermine", "default", envir = .GlobalEnv)

# Erzeuge Skript "DozentenSkript", "StudierendenSkript" oder "LösungsSkript": 
makeSkriptOfType("DozentenSkript") 
```
```{r ggplot2Setup, eval=TRUE, echo=FALSE, include=FALSE}
library(ggplot2)
# ggformula, also ggplot2 muss noch etwas konfiguriert werden.
theme.fom <- theme_classic(22*1.02)
theme.fom <- theme.fom
theme_set(
  theme.fom  
)
```
```{r setUpChildren, eval=TRUE, include=FALSE}
ChildList <- c(
    {paste0("QFM-Organisatorisches",
            if_else(my.options$get("layouttype") == "eufom", "-eufom",""),
            if_else(my.options$get("Virtuell"),"-Virtuell", ""),  # 60-min Klausur-Fassung
            '.Rmd')},
    {if_else(my.options$get("privateVorstellung"),
             'private/private-Vorstellung.Rmd', NULL)},
    # 'Organisatorisches/Hinweise.Rmd', 
    'Grundlagen-Wissenschaft.Rmd', 
    'Grundlagen-QuantDat.Rmd', 
    'Einfuehrung-R.Rmd',
    'EDA.Rmd',
    'Regression.Rmd',
    'Normalverteilung.Rmd',
    'Inferenz.Rmd',
    # 'Inferenz-Beispiele.Rmd',  # -> Anhang!
    # 'Datenhandling.Rmd',  # -> Anhang!
    'Abschluss.Rmd'
)
if (FALSE) { # Zum Debuggen einfach auf TRUE setzen!
  ChildList <- c(
    "Grundlagen-Wissenschaft", 
    "Abschluss"
  )
}
IncludeChildList <- file.path('Inhalte', na.omit(ChildList))
```

```{r setup_data, include=FALSE}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Sichert zu, dass die entsprechenden Daten auch vorhanden sind. 
# Ggf. werden sie von dem übergebenden Link geladen und lokal gespeichert.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
tips <- assertData("tips.csv", "https://goo.gl/whKjnl")

# ---------------------------------------------------------------------------
```

```{r child = IncludeChildList}
```

```{r finalize, include=FALSE}
# ---------------------------------------------------------------------------
# Setzt einige Parameter zurück
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
finalizePrelude()
```
