---
title: "Wiederholung"
---

```{r setup, include=FALSE}
# ---------------------------------------------------------------------------
# Einige Funktionen und Variabeln sind in die Datei 'prelude.R' ausgelagert.
# Diese werden hier nachgeladen und angepasst.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
source("prelude.R")
initPrelude(
    "WM-",        # Prefix für Terminlisten etc.
    TRUE           # Soll geprüft werden ob alle Pakete installiert sind?
)

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Sichert zu, dass die entsprechenden Daten auch vorhanden sind. 
# Ggf. werden sie von dem übergebenden Link geladen und lokal gespeichert.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# tips <- assertData("tips.csv", "https://goo.gl/whKjnl")


# ---------------------------------------------------------------------------
```

```{r localKnitrButtonSetup, eval=TRUE, echo=FALSE, include=FALSE}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Einstellungen für den Fall, dass man den knitr-Button nutzt. Sonst bitte
# 'eval=FALSE' einstellen!
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

assign("abschluss", FALSE, envir = .GlobalEnv)

my.options$set(
  privateVorstellung = FALSE,  # Zeige die Private Vorstellung
  showVorlesungsplan = FALSE,  # Zeige den Vorlesungsplan
  showuseR = FALSE,
  Corona = FALSE
)

assign("UseCache", TRUE)  # immer mal wieder auf FALSE setzen
assign("Vorlesungstermine", "default")

if (!exists("prelude.rendertools")) {
    loadPrelude("prelude_rendertools.R")
}

createPrivateYaml("FOM", "SoSe 2023", "WM")

options(scipen = 10, digits = 2) # scipen = 100 ist zu viel, dann werden die p-Werte mit x Nachkommastellen angezeigt

UseCache <<- FALSE
makeDozi()        # Erzeuge Dozentenskript
#makeStudi()       # Erzeuge Studentenskript
#makeLsgSkript()   # Erzeuge Lösungsskript
```


```{r child = './Inhalte/Wiederholung/Wiederholungs-WM.Rmd'}
```

```{r finalize, include=FALSE}
# ---------------------------------------------------------------------------
# Setzt einige Parameter zurück
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
finalizePrelude()
```