---
title: "Wissenschaftliche Methoden -- Quantitative Datenanalyse"
tag:
    - bachelor
    - sesmill
    - shiny
    - wmqd
---

```{r setup, include=FALSE}
# ---------------------------------------------------------------------------
# Einige Funktionen und Variabeln sind in die Datei 'prelude.R' ausgelagert.
# Diese werden hier nachgeladen und angepasst.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
source("prelude.R")
initPrelude(
    "WMQD-",       # Prefix für Terminlisten etc.
    TRUE           # Soll geprüft werden ob alle Pakete installiert sind?
)
```
```{r localKnitrButtonSetup, eval=!RENDEREDBYSCRIPT, echo=FALSE, include=FALSE}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Einstellungen für den Fall, dass man den knitr-Button nutzt. Sonst bitte
# 'eval=FALSE' einstellen!
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if (!exists("prelude.rendertools")) {
    loadPrelude("prelude_rendertools.R")
}

privateVorstellung <<- FALSE   # Zeige die Private Vorstellung
showVorlesungsplan <<- FALSE  # Zeige den Vorlesungsplan
showuseR <<- FALSE
UseCache <<- TRUE  # Achtung: Immer mal wieder Cache löschen/auf FALSE setzen

Vorlesungstermine <<- ""

createPrivateYaml("FOM", "WiSe 2020", "")

# Erzeuge Skript "DozentenSkript", "StudierendenSkript" oder "LösungsSkript": 
makeSkriptOfType("LösungsSkript")
```
```{r ggplot2Setup, eval=TRUE, echo=FALSE, include=FALSE}
library(ggplot2)
# ggformula, also ggplot2 muss noch etwas konfiguriert werden.
theme.fom <- theme_classic(22*1.02)
theme.fom <- theme.fom + theme(
    # plot.background = element_rect(fill = "#CDEBE0"),
    # panel.background = element_rect(fill = "#CDEBE0", colour = "#009981")
  )
theme_set(
  theme.fom  
)
```
```{r setUpChildren, eval=TRUE, include=FALSE}
childrenToInclude <- c(
    "WMQD-Organisatorisches", "Grundlagen-Wissenschaft", "Grundlagen-QuantDat", "Einfuehrung-R",
    "EDA", "Normalverteilung", "Regression", "Inferenz", "Kausalanalyse", "Inferenz-Beispiele", "Abschluss"
)

## Test! (TRUE oder FALSE ändern!)
if (FALSE) {
  childrenToInclude <- c(
    "Datenhandling"
  )
  privateVorstellung <<- FALSE
  }
##

includeChild <- function(name, children=childrenToInclude, all=FALSE) {
    all | ifelse(name %in% children, TRUE, FALSE)
}
```

```{r setup_data, include=FALSE}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Sichert zu, dass die entsprechenden Daten auch vorhanden sind. 
# Ggf. werden sie von dem übergebenden Link geladen und lokal gespeichert.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
tips <- assertData("tips.csv", "https://goo.gl/whKjnl")

# ---------------------------------------------------------------------------

child=DEPRECATED <<-FALSE

```

```{r child = './Inhalte/WMQD-Organisatorisches.Rmd', eval=includeChild("WMQD-Organisatorisches")}
```

```{r child = './private/private-Vorstellung.Rmd', eval = privateVorstellung}
```

```{r child = './Inhalte/Organisatorisches/Hinweise.Rmd', eval=includeChild("Hinweise")}
```

```{r child = './Inhalte/Grundlagen-Wissenschaft.Rmd', eval=includeChild("Grundlagen-Wissenschaft")}
```

```{r child = './Inhalte/Grundlagen-QuantDat.Rmd', eval=includeChild("Grundlagen-QuantDat")}
```

```{r child = './Inhalte/Einfuehrung-R.Rmd', eval=includeChild("Einfuehrung-R")}
```

```{r child = './Inhalte/EDA.Rmd', eval=includeChild("EDA")}
```

```{r child = './Inhalte/Normalverteilung.Rmd', eval=includeChild("Normalverteilung")}
```

```{r child = './Inhalte/Regression.Rmd', eval=includeChild("Regression")}
```

```{r child = './Inhalte/Inferenz.Rmd', eval=includeChild("Inferenz")}
```

```{r child = './Inhalte/Kausalanalyse.Rmd', eval=includeChild("Kausalanalyse")}
```

```{r child = './Inhalte/Inferenz-Beispiele.Rmd', eval=includeChild("Inferenz-Beispiele")}
```

```{r child = './Inhalte/Datenhandling.Rmd', eval=FALSE}
```

```{r child = './Inhalte/Abschluss.Rmd', eval=includeChild("Abschluss")}
```

```{r finalize, include=FALSE}
# ---------------------------------------------------------------------------
# Setzt einige Parameter zurück
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
finalizePrelude()
```
