---
title: "Wissenschaftliche Methodik"
tag:
    - master
    - MasterNeu
    - sesmill
    # - exclude-crazy-norman
    - shiny
---

```{r setup, include=FALSE}
# ---------------------------------------------------------------------------
# Einige Funktionen und Variabeln sind in die Datei 'prelude.R' ausgelagert.
# Diese werden hier nachgeladen und angepasst.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
source("prelude.R")
initPrelude(
    "WM-",         # Prefix für Terminlisten etc.
    TRUE           # Soll geprüft werden ob alle Pakete installiert sind?
)
```
```{r localKnitrButtonSetup, eval=!get("RENDEREDBYSCRIPT" ), echo=FALSE, include=FALSE}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Einstellungen für den Fall, dass man den knitr-Button nutzt. Sonst bitte
# 'eval=FALSE' einstellen!
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if (!exists("prelude.rendertools")) {
    loadPrelude("prelude_rendertools.R")
}

assign("abschluss", FALSE, envir = .GlobalEnv)
assign("WDH", "", envir = .GlobalEnv)

my.options$set(
  privateVorstellung = FALSE,   # Zeige die Private Vorstellung
  showVorlesungsplan = FALSE,   # Zeige die Vorlesungstermine -> In der Datei WM-default.Rmd anpassen
  showuseR  = FALSE,            # Folien mit useR-Umfragen anzeigen oder ausschließen
  Virtuell    = FALSE,
  MasterNeu = TRUE             # Überarbeitung Master mg, kl
)

assign("UseCache", TRUE)       # immer mal wieder auf FALSE setzen
assign("Vorlesungstermine", "default")

# Standardeinstellung ("Dozent", "Semester", "FOM Standort")
# muss beim Kompilieren mit Knit-Button korrekt eingestellt werden
createPrivateYaml("Dozent*in", "SoSe 2024", "FOM") 

# Erzeuge Skript , "StudierendenSkript" oder "LösungsSkript": 
#makeSkriptOfType("DozentenSkript")
#makeSkriptOfType("StudierendenSkript")
makeSkriptOfType("LösungsSkript")
```
```{r ggplot2Setup, eval=TRUE, echo=FALSE, include=FALSE}
library(ggsci)
library(ggplot2)
# ggformula, also ggplot2 muss noch etwas konfiguriert werden.
theme.fom <- theme_classic(22*1.02)
theme.fom <- theme.fom
theme_set(
  theme.fom  
)
```
```{r setup_data, include=FALSE}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Sichert zu, dass die entsprechenden Daten auch vorhanden sind. 
# Ggf. werden sie von dem übergebenden Link geladen und lokal gespeichert.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
tips <- assertData("tips.csv", "https://goo.gl/whKjnl")

# ---------------------------------------------------------------------------
```
```{r setUpChildren, eval=TRUE, include=FALSE}
ChildList <- c(
    {if_else(my.options$get("Virtuell"),
             'WM-Organisatorisches-Virtuell.Rmd',  # 60-min Klausur-Fassung
             'WM-Organisatorisches.Rmd')},
    {if_else(my.options$get("privateVorstellung"),
             'private/private-Vorstellung.Rmd', NULL)},
    'Organisatorisches/Hinweise.Rmd', 
    'Grundlagen-Wissenschaft.Rmd', 
    'Grundlagen-QuantDat.Rmd',
    {if_else(my.options$get("MasterNeu"),
            'KeinInhalt.Rmd', 'Einfuehrung-R.Rmd')},
    'EDA.Rmd',
    # 'Normalverteilung.Rmd', # --> Optional
    'Regression.Rmd',
    {if_else(my.options$get("MasterNeu"),  
              'KeinInhalt.Rmd', 'Inferenz.Rmd')},
    {if_else(my.options$get("MasterNeu"),  
              'Kausalanalyse.Rmd', 
              'Inferenz-Beispiele.Rmd')},
    # 'Datenhandling.Rmd',  # -> Anhang!
    'Abschluss.Rmd'
)
if (FALSE) { # Zum Debuggen einfach auf TRUE setzen!
  ChildList <- c(
#    'Organisatorisches/Hinweise.Rmd'
#    'Grundlagen-Wissenschaft.Rmd'
#    'Grundlagen-QuantDat.Rmd'
#    'Einfuehrung-R.Rmd'
#    'EDA.Rmd'
#    # 'Normalverteilung.Rmd', # --> Optional
    'Regression.Rmd'
#    'LogistischeRegression.Rmd'
#    # 'Inferenz.Rmd'        # gestrichen in MasterNeu
#    # 'Datenhandling.Rmd',  # -> Anhang!
#    'Kausalanalyse.Rmd'
#    'Inferenz-Beispiele.Rmd'
#    'Abschluss.Rmd'
  )
}
IncludeChildList <- file.path('Inhalte', na.omit(ChildList))
```


```{r child = IncludeChildList}
```


```{r finalize, include=FALSE}
# ---------------------------------------------------------------------------
# Setzt einige Parameter zurück
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
finalizePrelude()
```
