### FOM Charta

**Studierende**


- nutzen Lehre und Forschung an der FOM zusammen mit ihrer Praxiserfahrung zur Schärfung ihres analytisch konzeptionellen Denkens. Sie setzen sich kritisch und reflektiert mit wissenschaftlichen Ansätzen auseinander und transferieren diese lösungsorientiert und ganzheitlich verantwortlich auf unbekannte Situationen in ihre Berufswelt. Sie wissen um die Bedeutung von Ethik, Umwelt und Philanthropie im Bezug auf ihr Handeln.

- nutzen aktiv die Angebote der Lehrenden und der Lehrkoordination zur Bewältigung von Lernprozessen und zum gezielten Kompetenzmanagement. Dabei tragen sie durch aktive Selbstreflexion und Eigenverantwortlichkeit zu ihrer eigenen Persönlichkeits- und Kompetenzentwicklung und ihrem akademischen Werdegang bei.

- bringen sich aktiv, teils in Zusammenarbeit mit Mitstudierenden, in die Lehrveranstaltungen ein. Sie bereiten den Lernstoff kontinuierlich vor und nach, um die angestrebten Lernziele zu erreichen; hierzu holen sie sich aktiv Feedback ein. Durch konstruktives Feedback an Lehrende und Lehrkoordination gestalten sie die Lehre proaktiv mit. Sie erbringen die Prüfungsleistungen integer und selbstständig.

- kennen die Ziele ihres Studiums und setzen diese engagiert um. Sie setzen sich mit Prüfungsordnungen, Modulbeschreibungen und Lernmaterialien proaktiv auseinander und nutzen das FOM-Lernmanagementsystem.



### FOM Charta

**Lehrende**

- schaffen durch ihre fachliche, methodische und didaktische Kompetenz und (Praxis-)Erfahrung den Raum für die persönliche Entwicklung der Studierenden. Sie sind Vorbild bei der Herausbildung selbstständigen, akademischen, problemlösenden Denkens sowie kritischer Reflexion.

- berücksichtigen das Potenzial heterogener Bildungshintergründe und der beruflichen Erfahrungswelt der Studierenden. Sie wertschätzen die individuelle Persönlichkeit der Studierenden und binden diese in den Lehrdialog ein.

- initiieren, steuern und verknüpfen die Lernprozesse durch aktivierende, motivierende Lehre auf hohem wissenschaftlichem Niveau im Rahmen der FOM Transferdidaktik. Hierbei nutzen sie das Lehr-Lernmanagementsystem der FOM Hochschule sowie die relevanten Studienkonzepte, Modulbeschreibungen und Lehrmaterialien.

- machen Bewertungskriterien gegenüber den Studierenden vorab transparent und geben ihnen zeitnah und nachvollziehbar Rückmeldungen zum individuellen Leistungsstand.

- nutzen als Repräsentanten/-innen der FOM die internen Informations- und Leistungsangebote der Hochschule.
