```{r, include=FALSE}
# ---------------------------------------------------------------------------
#% maintainer:
#%   - Karsten Lübke
#%
# ---------------------------------------------------------------------------
source("../../prelude.R")
initPart(
    "Hinweise",  # Dateiname ohne Suffix
    "Organisatorisches"              # Verzeichnisname im Bilderverzeichnis 
    )
pathToImages = getPathToImages()
# ---------------------------------------------------------------------------

```

<!-- Bug? -->

### Bitte {exclude=virtuell}

- Stellen Sie ein Namensschild auf. 
- Seien Sie offen für das Thema.
- Haben Sie Respekt aber keine Angst vor der Schwierigkeit des Themas.
- Bereiten Sie den Lehrstoff von Anfang an kontinuierlich nach.
- Stellen Sie Fragen!
- Sie können Sich gerne während der Übungen unterhalten, aber nicht wenn ich etwas erkläre -- das ist u. a. auch unfair!
- Versuchen Sie die Übungen selbst zu lösen - der Lernerfolg ist ungleich größer, als wenn Sie die Lösung "abnicken". Für die Quizze wird ein Live-Feedback-System eingesetzt: [https://tweedback.de/](https://tweedback.de/)
**Nehmen Sie daran teil!**^[Siehe z.B. [Nguyen, K., & McDaniel, M. A. (2015). Using quizzing to assist student learning in the classroom: the good, the bad, and the ugly. Teaching of Psychology, 42(1), 87-92](https://doi.org/10.1177/0098628314562685).]
- Versuchen Sie Ablenkungen (Facebook, WhatsApp etc.) zu vermeiden.^[Siehe z.B. [Sana, F., Weston, T., & Cepeda, N. J. (2013). Laptop multitasking hinders classroom learning for both users and nearby peers. Computers & Education, 62, 24-31](https://doi.org/10.1016/j.compedu.2012.10.003).]
- Wenn möglich, bringen Sie einen Laptop mit R^[Installationsanleitung [hier](https://rawgit.com/luebby/Datenanalyse-mit-R/master/Installation/Install.html)] zu den Vorlesungsterminen mit.

<!-- Bug? -->

### Bitte {include-only=virtuell}

- Nehmen Sie unter Ihrem Namen an der virtuellen Veranstaltung teil.
- Seien Sie offen für das Thema.
- Haben Sie Respekt aber keine Angst vor der Schwierigkeit des Themas.
- Bereiten Sie den Lehrstoff von Anfang an kontinuierlich nach.
- Stellen Sie Fragen, nutzen Sie den Chat!
- Arbeiten Sie in Gruppen (Breakout-Sessions) aktiv zusammen. 
- Versuchen Sie die Übungen selbst zu lösen - der Lernerfolg ist ungleich größer, als wenn Sie die Lösung "abnicken". Für die Quizze wird ein Live-Feedback-System eingesetzt: [https://tweedback.de/](https://tweedback.de/)
**Nehmen Sie daran teil!**^[Siehe z.B. [Nguyen, K., & McDaniel, M. A. (2015). Using quizzing to assist student learning in the classroom: the good, the bad, and the ugly. Teaching of Psychology, 42(1), 87-92](https://doi.org/10.1177/0098628314562685).]
- Versuchen Sie Ablenkungen (Facebook, WhatsApp etc.) zu vermeiden.^[Siehe z.B. [Sana, F., Weston, T., & Cepeda, N. J. (2013). Laptop multitasking hinders classroom learning for both users and nearby peers. Computers & Education, 62, 24-31](https://doi.org/10.1016/j.compedu.2012.10.003).]

<!-- Bug? -->

### Hinweis

**Bleiben Sie dran!**

**Die Inhalte bauen aufeinander auf**, d.h., arbeiten Sie nach. Die angegebene Literatur ist frei verfügbar. Wenn Sie nicht **kontinuierlich nacharbeiten** wird es immer schwerer, da immer mehr Grundlagen fehlen.

Ich kann versuchen, es Ihnen zu erklären, ich kann es *nicht* für Sie verstehen. Daher: fragen Sie direkt in der nächsten Vorlesung nach, wenn Sie in der Nacharbeit etwas nicht verstanden haben.

Die Folien bilden die *Leinwand* der Vorlesung: sie werden *interaktiv* erklärt und ergänzt.



### Anleitung zum Unglücklichwerden {exclude=virtuell}

- Ich besuche die Vorlesung nicht, ich schaue Videos.
- Kontinuierlich nacharbeiten? Quatsch, ich lerne eine Woche vor der Klausur intensiv.
- Es reicht, wenn ich mit einem halben Ohr zuhöre -- ich spiele, chatte, surfe während der Vorlesung.^[vgl. [https://youtu.be/vJG698U2Mvo](https://youtu.be/vJG698U2Mvo)]
- Mitschreiben? Ich mache, wenn überhaupt, ein Foto. Hier nicht erlaubt!
- Selbstlernunterlagen und Literatur habe ich nicht nötig.
- Mir genügt die Übungsklausur zur Klausurvorbereitung -- falls eine angeboten wird.
- Übungen selber lösen? -- Es reicht, wenn ich die Lösung kenne.

Tun Sie dies in Ihrem eigenen Interesse bitte **nicht**. **Sie** können es **besser**! 

Siehe z.B. echte Tipps unter [Putnam, A. L., Sungkhasettee, V. W., & Roediger III, H. L. (2016). Optimizing learning in college: tips from cognitive psychology. Perspectives on Psychological Science, 11(5), 652-660.](https://doi.org/10.1177/1745691616645770)

### Data Literacy und Growth Mindset

In dieser Vorlesung geht es nicht um Mathematik oder Programmierung, und es ist auch nicht wichtig, ob Sie in der Schule darin gut oder schlecht waren. Es geht darum, Daten auf kritische Art und Weise zu sammeln, zu managen, zu bewerten und anzuwenden (**Data Literacy**).

**Sie** können datenkompetent werden!

Stark vereinfacht: Ihr Gehirn ist wie ein Muskel -- es wird stärker, wenn Sie es durch Übungen trainieren. Es kann Rückschläge geben, z.B. Übungen, die Sie nicht auf Anhieb verstehen. Resignieren Sie nicht! Arbeiten Sie daran, wachsen Sie (**Growth Mindset**).



